modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://github.com/xhanhh/ApocalypseMinimapHud/issues"
[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"

updateJSONURL="https://raw.githubusercontent.com/xhanhh/ApocalypseMinimapHud/refs/heads/1.20.1/updates.json"
displayURL="https://modrinth.com/project/apocalypseminimaphud"
logoFile="logo.png"
authors="${mod_authors}"

description='''${mod_description}'''

[modproperties.${mod_id}]
    catalogueImageIcon="logo.png"

[[dependencies.${mod_id}]]
    modId="forge"
    mandatory=true
    versionRange="${neo_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
modId="apocalypse"
mandatory=true
versionRange="[1.20.1-1.4.7-r,)"
ordering="NONE"
side="BOTH"